services:
  - type: web
    name: account-management-app
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/accounts/stats
    preDeployCommand: npm run db:push
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://root:1ExOZk7EVyqjIxO3XWofcyaKEYUfnwiq@dpg-d35r6gjlpnbc739ndt0-a/cloneacc_148x